//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TxFarmDiaryAI.Common {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TxFarmDiaryAI.Common.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Farming Diary Automation System with AI-OCR과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Application_Full_Name {
            get {
                return ResourceManager.GetString("Application_Full_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Farming Diary Automation System과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Application_Short_Name {
            get {
                return ResourceManager.GetString("Application_Short_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string btnRefresh {
            get {
                return ResourceManager.GetString("btnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string btnReload {
            get {
                return ResourceManager.GetString("btnReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scan과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string btnScan {
            get {
                return ResourceManager.GetString("btnScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to add image to cart due to an invalid index.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CART_APPEND_ERROR_INDEX {
            get {
                return ResourceManager.GetString("CART_APPEND_ERROR_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This item could not be added to your cart.
        ///(File access and format errors)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CART_APPEND_MISS {
            get {
                return ResourceManager.GetString("CART_APPEND_MISS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no images to add to the cart.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CART_APPEND_NOIMAGE {
            get {
                return ResourceManager.GetString("CART_APPEND_NOIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The image has been added to the cart.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CART_APPEND_SUCCESS {
            get {
                return ResourceManager.GetString("CART_APPEND_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The image is already in your cart.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CART_APPEND_WARRING_EXISTS {
            get {
                return ResourceManager.GetString("CART_APPEND_WARRING_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to delete the images in the selected cart?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CART_DELETE_QUESTION {
            get {
                return ResourceManager.GetString("CART_DELETE_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is already a date entered, and the date you are trying to specify is different.
        ///
        ///Do you want to continue?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DATEDIFF_APPLY_QUESTION {
            get {
                return ResourceManager.GetString("DATEDIFF_APPLY_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified date and the date entered in the document are different.
        ///
        ///Do you want to continue?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DATEDIFF_NOTEQUALS_QUESTION {
            get {
                return ResourceManager.GetString("DATEDIFF_NOTEQUALS_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Farm and address information was not entered.
        ///Please check again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIARY_NOT_ADDR {
            get {
                return ResourceManager.GetString("DIARY_NOT_ADDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No date has been specified.
        ///Please check again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIARY_NOT_DATE {
            get {
                return ResourceManager.GetString("DIARY_NOT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detailed task information has not been entered.
        ///Please check again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIARY_NOT_DETAIL {
            get {
                return ResourceManager.GetString("DIARY_NOT_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The task step (task name) information has not been entered.
        ///Please check again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIARY_NOT_TASK {
            get {
                return ResourceManager.GetString("DIARY_NOT_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Would you like to save the currently entered document?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIARY_SAVE_QUESTION {
            get {
                return ResourceManager.GetString("DIARY_SAVE_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified file does not exist.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FILE_NOTEXIST {
            get {
                return ResourceManager.GetString("FILE_NOTEXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hello world!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelloText {
            get {
                return ResourceManager.GetString("HelloText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no images to copy.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IMAGE_COPY_NOIMAGE {
            get {
                return ResourceManager.GetString("IMAGE_COPY_NOIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no images to cut.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IMAGE_CUT_NOIMAGE {
            get {
                return ResourceManager.GetString("IMAGE_CUT_NOIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to cut the image?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IMAGE_CUT_QUESTION {
            get {
                return ResourceManager.GetString("IMAGE_CUT_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no images to delete.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IMAGE_DELETE_NOIMAGE {
            get {
                return ResourceManager.GetString("IMAGE_DELETE_NOIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no images to edit.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IMAGE_EDIT_NOIMAGE {
            get {
                return ResourceManager.GetString("IMAGE_EDIT_NOIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete the image?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IMAGE_EDIT_QUESTION {
            get {
                return ResourceManager.GetString("IMAGE_EDIT_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The image format is not supported (MemoryBmp).과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IMAGE_FORMAT_MEMORYBMP {
            get {
                return ResourceManager.GetString("IMAGE_FORMAT_MEMORYBMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The image format is not supported (Emf).과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IMAGE_FORMAT_NOTSUPPORT_EMF {
            get {
                return ResourceManager.GetString("IMAGE_FORMAT_NOTSUPPORT_EMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The image format is not supported (Icon).과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IMAGE_FORMAT_NOTSUPPORT_ICON {
            get {
                return ResourceManager.GetString("IMAGE_FORMAT_NOTSUPPORT_ICON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The image format is not supported (Wmf).과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IMAGE_FORMAT_NOTSUPPORT_WMF {
            get {
                return ResourceManager.GetString("IMAGE_FORMAT_NOTSUPPORT_WMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The image format is unknown.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IMAGE_FORMAT_UNKNOWN {
            get {
                return ResourceManager.GetString("IMAGE_FORMAT_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unsupported image file formats과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IMAGE_NOTSUPPORT {
            get {
                return ResourceManager.GetString("IMAGE_NOTSUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no images to paste.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IMAGE_PASTE_NOIMAGE {
            get {
                return ResourceManager.GetString("IMAGE_PASTE_NOIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The image file to be saved has no extension.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IMAGE_SAVE_NOFILEEXT {
            get {
                return ResourceManager.GetString("IMAGE_SAVE_NOFILEEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no images to save.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IMAGE_SAVE_NOIMAGE {
            get {
                return ResourceManager.GetString("IMAGE_SAVE_NOIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The image size is too large.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IMAGE_SIZE_TOOLARGE {
            get {
                return ResourceManager.GetString("IMAGE_SIZE_TOOLARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The image size is too small.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IMAGE_SIZE_TOOSMALL {
            get {
                return ResourceManager.GetString("IMAGE_SIZE_TOOSMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblUserID {
            get {
                return ResourceManager.GetString("lblUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MENU_FILTER {
            get {
                return ResourceManager.GetString("MENU_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MENU_SAVE_FOLDER {
            get {
                return ResourceManager.GetString("MENU_SAVE_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Work Farm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MENU_WORK_FARM {
            get {
                return ResourceManager.GetString("MENU_WORK_FARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is an image loaded into the Picture object.
        ///Would you like to load  new one?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PICTURE_LOADED_QUESTION {
            get {
                return ResourceManager.GetString("PICTURE_LOADED_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unsupported file extension.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SAVE_FILEEXT_NOTSUPPORT {
            get {
                return ResourceManager.GetString("SAVE_FILEEXT_NOTSUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SaveID {
            get {
                return ResourceManager.GetString("SaveID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scanner과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Scanner {
            get {
                return ResourceManager.GetString("Scanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while searching for the scanner.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SCANNER_FIND_ERROR {
            get {
                return ResourceManager.GetString("SCANNER_FIND_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Searching for scanner device...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SCANNER_FIND_FINDING {
            get {
                return ResourceManager.GetString("SCANNER_FIND_FINDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No connected scanner found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SCANNER_FIND_NOTFOUND {
            get {
                return ResourceManager.GetString("SCANNER_FIND_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scanner found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SCANNER_FIND_SUCCESS {
            get {
                return ResourceManager.GetString("SCANNER_FIND_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to import scanned image.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SCANNER_SCAN_NOTFOUND {
            get {
                return ResourceManager.GetString("SCANNER_SCAN_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Starting the scan...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SCANNER_SCAN_START {
            get {
                return ResourceManager.GetString("SCANNER_SCAN_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scan is complete.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SCANNER_SCAN_SUCCESS {
            get {
                return ResourceManager.GetString("SCANNER_SCAN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connecting to scanner...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SCANNER_SELECT_CONN {
            get {
                return ResourceManager.GetString("SCANNER_SELECT_CONN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to connect to the selected scanner.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SCANNER_SELECT_ERROR {
            get {
                return ResourceManager.GetString("SCANNER_SELECT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select a scanner.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SCANNER_SELECT_PLEASE {
            get {
                return ResourceManager.GetString("SCANNER_SELECT_PLEASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The template file for the recognized document does not exist.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TEMPLATE_FILE_NOT_EXIST {
            get {
                return ResourceManager.GetString("TEMPLATE_FILE_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Program Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Program_Name {
            get {
                return ResourceManager.GetString("Title_Program_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
    }
}
